export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  GATE_OPERATOR = 'GATE_OPERATOR',
  SALES_STAFF = 'SALES_STAFF',
  CASHIER = 'CASHIER',
}

export enum WorkflowStatus {
  ENTERED = 'ENTERED',
  SALES_PENDING = 'SALES_PENDING',
  SALES_COMPLETE = 'SALES_COMPLETE',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_COMPLETE = 'PAYMENT_COMPLETE',
  COMMISSION_PENDING = 'COMMISSION_PENDING',
  COMMISSION_COMPLETE = 'COMMISSION_COMPLETE',
  COMPLETED = 'COMPLETED',
}

export enum OrderType {
  ORDER = 'ORDER',
  HAND_DELIVERY = 'HAND_DELIVERY',
}

export enum PaymentMode {
  CC = 'CC',
  IC = 'IC',
  FC = 'FC',
}

export enum CommissionRecipientType {
  DRIVER = 'DRIVER',
  GUIDE = 'GUIDE',
  LOCAL_AGENT = 'LOCAL_AGENT',
  COMPANY = 'COMPANY',
}

export enum BillingOrderStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
}

export enum AuditAction {
  VEHICLE_ENTRY_CREATED = 'VEHICLE_ENTRY_CREATED',
  VEHICLE_ENTRY_UPDATED = 'VEHICLE_ENTRY_UPDATED',
  SALE_CREATED = 'SALE_CREATED',
  SALE_UPDATED = 'SALE_UPDATED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_UPDATED = 'PAYMENT_UPDATED',
  COMMISSION_CALCULATED = 'COMMISSION_CALCULATED',
  COMMISSION_OVERRIDDEN = 'COMMISSION_OVERRIDDEN',
  STATUS_CHANGED = 'STATUS_CHANGED',
  USER_CREATED = 'USER_CREATED',
  LOGIN = 'LOGIN',
  BILLING_ORDER_CREATED = 'BILLING_ORDER_CREATED',
  BILLING_ORDER_UPDATED = 'BILLING_ORDER_UPDATED',
  BILLING_ORDER_DELETED = 'BILLING_ORDER_DELETED',
}
