services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/fbawithfasih/sangemarmar-vts-backend:latest
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - '3000:3000'

volumes:
  postgres_data:
